#!/bin/bash

./start-mongo-as-single-node.sh
cd ..
./sbt test 
cd script

echo Done. Run generate-intellij-project-files.sh if you want to use IntelliJ Idea or generate-eclipse-project-files.sh if you want to use Eclipse.
